---
driver:
  name: vagrant
  customize:
    memory: 1024

verifier:
  root_path: '/tmp/verifier'
  sudo: true

provisioner:
  name: chef_zero
  always_update_cookbooks: true

platforms:
  - name: centos-7
  - name: centos-8
  - name: ubuntu-16.04
    attributes:
      nginx:
        install_method: source
  - name: ubuntu-18.04
  - name: ubuntu-20.04

suites:
  - name: http
    run_list:
      - recipe[acme_server]
      - recipe[acme_client::http]
    attributes:
      acme:
        dir: https://127.0.0.1:14000/dir
        contact:
          - mailto:admin@example.com
